### ISSUE TITLE
Czekaj... Co?

### ISSUE THREAD

**Issue by legacy6vz** [WukongDEV/Strona-Mesika#2]
Jak można Leakować coś co jest dostępne publiczne, wystarczy że wciśniesz Ctrl+Shift+I i masz wszystkie pliki

Do Wukonga: Opanuj się z tym publikowaniem kodu, twoja strona na 000webhost ssie mocno, podajesz się za Fullstack developera, mimo tego że jesteś fullstackoverflow pseudolem

#wukongisoverparty

**Comment by mesiik** [comment]
Takim zachowaniem tylko pokazujesz swoj poziom, publikujesz prace innych bo sam bys nic nie zrobil (do wukonga)

**Comment by Mopsior** [comment]
**#wukongisoverparty**

**Comment by m1chi-0** [comment]
Normalni ludzie mają flow, a Wukong ma tylko low

**#wukongisoverparty**

**Comment by Wuukong** [comment]
psy

**Comment by legacy6vz** [comment]
Widać Hipokryzje

**Comment by kolekcjo1ner** [comment]
> Widać Hipokryzje

Nie umie przyjąć krytyki

**Comment by legacy6vz** [comment]
Brak RIGCZu
