### ISSUE TITLE
wukong pro dev

### ISSUE THREAD

**Issue by ghost** [WukongDEV/Strona-Mesika#4]
siema, wukong, znalazlem twojego starego bota i powiem ci ze kod jest gorszy niz zine v1, a to juz wyczyn takze gratulacje X D
tutaj link do tego pseudolstwa: https://cutt.ly/cQI3llj
#wukongisoverparty

**Comment by Wuukong** [comment]
nie miałem nigdy bota i nie wejdę w ten link

**Comment by ghost** [comment]
miales miales tylko nie pamietasz
